package ingest

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/user/safeanalyze/pkg/config"
)

// Formatter prepares sanitized code for AI ingestion.
type Formatter struct {
	cfg config.OutputConfig
}

// NewFormatter creates a formatter from config.
func NewFormatter(cfg config.OutputConfig) *Formatter {
	return &Formatter{cfg: cfg}
}

// FileRecord represents a single file for ingestion.
type FileRecord struct {
	Path    string `json:"path"`
	Content string `json:"content"`
	Size    int    `json:"size"`
}

// Run walks the sanitized directory and produces formatted output.
func (f *Formatter) Run(dir string) ([]FileRecord, error) {
	var records []FileRecord

	err := filepath.WalkDir(dir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}

		rel, err := filepath.Rel(dir, path)
		if err != nil {
			return err
		}

		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}

		records = append(records, FileRecord{
			Path:    rel,
			Content: string(content),
			Size:    len(content),
		})
		return nil
	})

	sort.Slice(records, func(i, j int) bool {
		return records[i].Path < records[j].Path
	})

	return records, err
}

// WriteOutput writes formatted records to disk.
func (f *Formatter) WriteOutput(records []FileRecord, outDir string) error {
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return err
	}

	switch f.cfg.Format {
	case "json":
		return f.writeJSON(records, outDir)
	case "plain":
		return f.writePlain(records, outDir)
	default:
		return f.writeMarkdown(records, outDir)
	}
}

func (f *Formatter) writeMarkdown(records []FileRecord, outDir string) error {
	if f.cfg.SingleFile {
		var b strings.Builder
		b.WriteString("# Sanitized Codebase\n\n")
		b.WriteString("> Generated by safeanalyze. Comments stripped, non-ASCII removed.\n\n")

		if f.cfg.IncludeFileTree {
			b.WriteString("## File Tree\n\n```\n")
			for _, r := range records {
				b.WriteString(r.Path)
				b.WriteByte('\n')
			}
			b.WriteString("```\n\n")
		}

		for _, r := range records {
			ext := filepath.Ext(r.Path)
			if ext == "" {
				ext = "txt"
		}
			b.WriteString(fmt.Sprintf("## %s\n\n```%s\n%s\n```\n\n", r.Path, ext, r.Content))
		}

		return os.WriteFile(filepath.Join(outDir, "ingest.md"), []byte(b.String()), 0644)
	}

	// Multi-file: index + individual files
	var idx strings.Builder
	idx.WriteString("# Sanitized Codebase Index\n\n")

	for _, r := range records {
		idx.WriteString(fmt.Sprintf("- [%s](%s.md)\n", r.Path, filepath.ToSlash(r.Path)))

		safeName := strings.ReplaceAll(r.Path, string(os.PathSeparator), "_")
		outPath := filepath.Join(outDir, safeName+".md")

		var b strings.Builder
		ext := filepath.Ext(r.Path)
		if ext == "" {
			ext = "txt"
		}
		b.WriteString(fmt.Sprintf("# %s\n\n```%s\n%s\n```\n", r.Path, ext, r.Content))

		if err := os.MkdirAll(filepath.Dir(outPath), 0755); err != nil {
			return err
		}
		if err := os.WriteFile(outPath, []byte(b.String()), 0644); err != nil {
			return err
		}
	}

	return os.WriteFile(filepath.Join(outDir, "index.md"), []byte(idx.String()), 0644)
}

func (f *Formatter) writePlain(records []FileRecord, outDir string) error {
	if f.cfg.SingleFile {
		var b strings.Builder
		for _, r := range records {
			b.WriteString(fmt.Sprintf("===== %s =====\n", r.Path))
			b.WriteString(r.Content)
			b.WriteString("\n\n")
		}
		return os.WriteFile(filepath.Join(outDir, "ingest.txt"), []byte(b.String()), 0644)
	}

	for _, r := range records {
		safeName := strings.ReplaceAll(r.Path, string(os.PathSeparator), "_")
		outPath := filepath.Join(outDir, safeName+".txt")
		if err := os.MkdirAll(filepath.Dir(outPath), 0755); err != nil {
			return err
		}
		if err := os.WriteFile(outPath, []byte(r.Content), 0644); err != nil {
			return err
		}
	}
	return nil
}

func (f *Formatter) writeJSON(records []FileRecord, outDir string) error {
	// Simple JSON serialization without external dependency
	var b strings.Builder
	b.WriteString("[\n")
	for i, r := range records {
		b.WriteString("  {\n")
		b.WriteString(fmt.Sprintf("    \"path\": %q,\n", r.Path))
		b.WriteString(fmt.Sprintf("    \"size\": %d,\n", r.Size))
		// Escape content for JSON
		b.WriteString("    \"content\": ")
		b.WriteString(jsonEscape(r.Content))
		b.WriteString("\n  }")
		if i < len(records)-1 {
			b.WriteString(",")
		}
		b.WriteString("\n")
	}
	b.WriteString("]\n")
	return os.WriteFile(filepath.Join(outDir, "ingest.json"), []byte(b.String()), 0644)
}

func jsonEscape(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			b.WriteString(`\"`)
		case '\\':
			b.WriteString(`\\`)
		case '\b':
			b.WriteString(`\b`)
		case '\f':
			b.WriteString(`\f`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			if r < 0x20 {
				b.WriteString(fmt.Sprintf(`\u%04x`, r))
			} else {
				b.WriteRune(r)
			}
		}
	}
	b.WriteByte('"')
	return b.String()
}
